# -----------------------------------------------------------------------
# Configuration file for https://travis-ci.org/elastic/elasticsearch-ruby
# -----------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

branches:
  only:
    - master
    - 6.x
    - 5.x
    - 2.x
    - travis

matrix:
  include:

    # Unit tests
    - rvm: ruby-head
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.5.0
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.4.1
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.3.4
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.2.5
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: jruby-9.1.12.0
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    # Integration tests
    - rvm: 2.5.0
      jdk: oraclejdk8
      env: DEBUG=y TEST_SUITE=integration

  allow_failures:
    - rvm: ruby-head
      jdk: oraclejdk8
      env: TEST_SUITE=unit

before_install:
  - ls $PWD
  - gem update --system
  - gem --version
  - gem install bundler -v 1.16.1
  - bundle version
  - curl -sS https://snapshots.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0-alpha1-SNAPSHOT.tar.gz | tar xz -C /tmp
  - rake setup
  - rake elasticsearch:update
  - bundle install
  - >
    [[ -n "$TEST_SUITE" ]] && [[ "$TEST_SUITE" == "integration" ]] &&
    TEST_CLUSTER_COMMAND=/tmp/elasticsearch-7.0.0-alpha1-SNAPSHOT/bin/elasticsearch
    bundle exec rake -I elasticsearch-extensions/lib test:cluster:start || true

install:
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:$TEST_SUITE

notifications:
  disable: true
